version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
    - mv target/spring-boot-todo-rest-api-cicd-0.0.1-SNAPSHOT.jar spring-boot-todo-rest-api-cicd-0.0.1-SNAPSHOT.jar
    - echo Buid package completion
artifacts:
  files:
    - spring-boot-todo-rest-api-cicd-0.0.1-SNAPSHOT.jar
    - .ebextensions/**/*


